--
-- PostgreSQL database dump
--

\restrict H1jtJaSkUGNtVqcnZWeK0QxdF6Z3Rf1QxnbMYxp1aGbPOMrgfKNhh3I64Y4sMPM

-- Dumped from database version 14.20
-- Dumped by pg_dump version 14.20

-- Started on 2025-12-26 21:02:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 16396)
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    featured boolean,
    image character varying(255),
    name character varying(255),
    price double precision,
    short_description character varying(255),
    short_info character varying(150),
    description character varying(255)
);


--
-- TOC entry 209 (class 1259 OID 16395)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3305 (class 0 OID 16396)
-- Dependencies: 210
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (id, featured, image, name, price, short_description, short_info, description) FROM stdin;
8	f	https://images-na.ssl-images-amazon.com/images/I/61zuR3UMnWL._AC_UL375_SR375,375_.jpg	External SSD 1TB	159	Ultra-fast data transfer in a compact design.	Premium quality guaranteed by UcuzBurada.	External 1TB SSD with fast data transfer and compact design
9	f	https://m.media-amazon.com/images/I/715pvx8UWrL.jpg	Laptop Stand	34	Improved posture with adjustable height levels.	Premium quality guaranteed by UcuzBurada.	Adjustable laptop stand for better posture and cooling
10	f	https://m.media-amazon.com/images/I/71HdLDJEEUL._AC_UF350,350_QL80_.jpg	Bluetooth Speaker	79	Deep bass and portable sound for every room.	Premium quality guaranteed by UcuzBurada.	Portable Bluetooth speaker with powerful sound and deep bass
11	f	https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop&q=80	Smart Watch	199	Track your health and stay connected all day.	Premium quality guaranteed by UcuzBurada.	Smart watch with fitness tracking, heart rate monitor and notifications
12	f	https://m.media-amazon.com/images/I/51vSsrUqWcL._AC_UF1000,1000_QL80_.jpg	Power Bank	49	Large capacity battery for your mobile devices.	Premium quality guaranteed by UcuzBurada.	High capacity power bank for fast charging mobile devices
1	t	https://m.media-amazon.com/images/I/71EW1+0MNAL.jpg	Gaming Laptop	1299	High-performance gaming with ultra-fast graphics.	Ultra-fast performance for pro gamers.	High performance gaming laptop suitable for modern games and daily use
2	f	https://wraithesports.com/cdn/shop/files/VXE_MAD_R_beyaz.jpg?v=1739948377&width=1500	Wireless Mouse	49	Silent clicks and ergonomic design for daily use.	Ergonomic design for long working hours.	Wireless mouse with ergonomic design and long battery life
3	f	https://m.media-amazon.com/images/I/61Uf-IyG3uL._UF1000,1000_QL80_.jpg	Mechanical Keyboard	139	Tactile feedback with customizable RGB lighting.	Premium quality guaranteed by UcuzBurada.	Mechanical keyboard with RGB lighting and fast response switches
4	f	https://m.media-amazon.com/images/I/81gMjOO-kyL._AC_UF894,1000_QL80_.jpg	27' Monitor	299	Crystal clear 4K resolution for professional work.	Crystal clear 4K visuals for creative work.	27 inch full HD monitor with sharp colors and smooth display
5	f	https://m.media-amazon.com/images/I/713f2wSRx1L._AC_UF1000,1000_QL80_.jpg	USB-C Hub	39	All-in-one connectivity for your modern laptop.	Premium quality guaranteed by UcuzBurada.	USB-C hub for laptops with HDMI, USB and charging support
6	f	https://images.unsplash.com/photo-1599669454699-248893623440?w=600&h=600&fit=crop&q=80	Gaming Headset	89	Immersive 7.1 surround sound with noise cancellation.	Immersive sound with noise cancellation.	Gaming headset with surround sound and noise cancelling microphone
7	f	https://m.media-amazon.com/images/I/51GX98P34aL.jpg	Webcam HD	59	Crystal clear 1080p video for smooth meetings.	Premium quality guaranteed by UcuzBurada.	HD webcam ideal for video calls, meetings and streaming
\.


--
-- TOC entry 3311 (class 0 OID 0)
-- Dependencies: 209
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 12, true);


--
-- TOC entry 3164 (class 2606 OID 16402)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


-- Completed on 2025-12-26 21:02:37

--
-- PostgreSQL database dump complete
--

\unrestrict H1jtJaSkUGNtVqcnZWeK0QxdF6Z3Rf1QxnbMYxp1aGbPOMrgfKNhh3I64Y4sMPM

